import Foundation
import SwiftExecSemantic

// This file is generated by Tools/SwiftExecWrapperGen in production.
public enum GeneratedSymbolTable {
    public static let swiftPrint = SymbolHasher.hash(namespace: .bridge, name: BuiltinSymbolName.print)
    public static let stringUppercased = SymbolHasher.hash(namespace: .bridge, name: BuiltinSymbolName.stringUppercased)
    public static let stringLowercased = SymbolHasher.hash(namespace: .bridge, name: BuiltinSymbolName.stringLowercased)
    public static let stringContains = SymbolHasher.hash(namespace: .bridge, name: BuiltinSymbolName.stringContains)
    public static let intInit = SymbolHasher.hash(namespace: .bridge, name: BuiltinSymbolName.intInit)
    public static let doubleInit = SymbolHasher.hash(namespace: .bridge, name: BuiltinSymbolName.doubleInit)
    public static let boolInit = SymbolHasher.hash(namespace: .bridge, name: BuiltinSymbolName.boolInit)
    public static let dateNow = SymbolHasher.hash(namespace: .bridge, name: BuiltinSymbolName.dateNow)
    public static let textInit = SymbolHasher.hash(namespace: .bridge, name: BuiltinSymbolName.textInit)

    public static let opAdd = SymbolHasher.hash(namespace: .operator, name: "+")
    public static let opSubtract = SymbolHasher.hash(namespace: .operator, name: "-")
    public static let opMultiply = SymbolHasher.hash(namespace: .operator, name: "*")
    public static let opDivide = SymbolHasher.hash(namespace: .operator, name: "/")
    public static let opEqual = SymbolHasher.hash(namespace: .operator, name: "==")
    public static let opLess = SymbolHasher.hash(namespace: .operator, name: "<")
    public static let opGreater = SymbolHasher.hash(namespace: .operator, name: ">")
    public static let opLessOrEqual = SymbolHasher.hash(namespace: .operator, name: "<=")
    public static let opGreaterOrEqual = SymbolHasher.hash(namespace: .operator, name: ">=")
    public static let opAnd = SymbolHasher.hash(namespace: .operator, name: "&&")
    public static let opOr = SymbolHasher.hash(namespace: .operator, name: "||")

    public static let all: Set<SymbolID> = [
        swiftPrint,
        stringUppercased,
        stringLowercased,
        stringContains,
        intInit,
        doubleInit,
        boolInit,
        dateNow,
        textInit,
        opAdd,
        opSubtract,
        opMultiply,
        opDivide,
        opEqual,
        opLess,
        opGreater,
        opLessOrEqual,
        opGreaterOrEqual,
        opAnd,
        opOr
    ]
}
